Issue/239/create edit event view
dbetka/harcmap pull request #245
Opened 2020-11-12 15:06 UTC by Bedpaw

2020-11-15 21:45 UTC, dbetka requested changes
To fix

2020-11-15 21:45 UTC, dbetka commented on src/utils/macros/routes.js
> +    icon: ICONS.map,
ICONS.edit

2020-11-15 21:45 UTC, dbetka commented on src/components/organisms/admin/edit-event.vue
> +          :disabled=true
`disabled` instead of `:disabled=true`

2020-11-15 21:45 UTC, dbetka commented on src/style/variables/colors/dark.sass
> +$color-text-disabled: rgba(palette.$Silver_Chalice, 0.5)
Check in dark mode

2020-11-15 21:45 UTC, dbetka commented on src/structures/app-event.js
>      this.mapPosition = {
It should like on backend

2020-11-18 20:01 UTC, Bedpaw commented on src/components/organisms/admin/edit-event.vue
> +          :disabled=true
done

2020-11-18 20:05 UTC, Bedpaw commented on src/style/variables/colors/dark.sass
> +$color-text-disabled: rgba(palette.$Silver_Chalice, 0.5)
looks ok

2020-11-18 20:11 UTC, Bedpaw commented on src/utils/macros/routes.js
> +    icon: ICONS.map,
done

2020-11-18 20:44 UTC, Bedpaw commented on src/structures/app-event.js
>      this.mapPosition = {
changed

2020-11-21 13:40 UTC, dbetka requested changes

2020-11-21 13:40 UTC, dbetka commented on src/components/organisms/admin/edit-event.vue
> +      />
Add assist message for "Klucz wydarzenia" field (see Figma)

2020-11-21 13:40 UTC, dbetka commented on src/components/organisms/admin/edit-event.vue
> +    },
Change this.message to 'Zapisanie nowych danych wydarzenia powiodło się.' and make focus out for save button on success.

2020-11-21 13:40 UTC, dbetka commented on src/store/event.js
> +    getEventBasicInformation: (state) => ({
`getEventBasicInformation` -> `getEventBasicInformations`

2020-11-21 13:40 UTC, dbetka commented on src/components/organisms/admin/edit-event.vue
> +        .then(this.setEvent)
this.setEvent doesn't work properly:

Example step-by-step:
1. sign in on admin account
2. go to /edit-event
3. put new event name
4. click save button
5. click on start button in footer
6. there is old event name

2020-11-21 13:40 UTC, dbetka commented on src/utils/macros/errors.js
> +  updateEvent: 'Something went wrong, event has not been updated',
Polish message put here

2020-11-21 13:44 UTC, Bedpaw commented on src/store/event.js
> +    getEventBasicInformation: (state) => ({
sorry, "information" is uncountable 😄

2020-11-21 18:56 UTC, Bedpaw commented on src/utils/macros/errors.js
> +  updateEvent: 'Something went wrong, event has not been updated',
done

2020-11-21 19:18 UTC, Bedpaw commented on src/components/organisms/admin/edit-event.vue
> +      />
done

2020-11-22 20:49 UTC, dbetka commented on src/store/event.js
> +    getEventBasicInformation: (state) => ({
Right xD

2020-11-22 20:51 UTC, dbetka approved these changes

2020-11-22 20:52 UTC, merged