Issue/263/clear sessions on startup
dbetka/harcmap pull request #266
Opened 2020-12-03 13:28 UTC by HenoJurek

Before merge we could add frontend support for cookie UUID

2020-12-10 21:59 UTC, dbetka requested changes

2020-12-10 21:59 UTC, dbetka commented on lib/passportConfig.js
> +    passReqToCallback: true,
What flag `passReqToCallback` means? It's not clear

2020-12-14 11:52 UTC, HenoJurek commented on lib/passportConfig.js
> +    passReqToCallback: true,
It's part of Passport framework. It pass request object to callback below

2021-01-11 20:19 UTC, dbetka commented on lib/passportConfig.js
> +    passReqToCallback: true,
add comment for it

2021-01-17 14:04 UTC, merged