Issue/196/map refresh timer
dbetka/harcmap pull request #270
Opened 2020-12-21 20:07 UTC by Bedpaw

Closes #196

2021-01-25 20:24 UTC, dbetka requested changes

2021-01-25 20:24 UTC, dbetka commented on src/components/molecules/countdown-timer.vue
> +  <div :style= "[minutes === 0 ? {color: 'red'} : {color: 'black'}]">
It should be in CSS classes - create 2 classes for 2 states and use these here.

2021-01-25 20:24 UTC, dbetka commented on src/components/molecules/countdown-timer.vue
> +import { getZeroPad } from 'utils/date';
What getZeroPad method doing? Name is not clear

2021-01-25 20:24 UTC, dbetka commented on src/components/molecules/countdown-timer.vue
> +      if (this.seconds === 0) {
Check moment.js plugin to manage time easier - https://momentjs.com/

2021-01-25 20:24 UTC, dbetka commented on src/components/molecules/countdown-timer.vue
> +      if (this.seconds === 0) {
You can add seconds and plugin will update minutes by itself.

2021-02-01 19:43 UTC, dbetka requested changes

2021-02-01 19:43 UTC, dbetka commented on src/dictionary/language/pl.js
> +  }
A comma is missing.

2021-02-01 20:12 UTC, dbetka commented on src/components/molecules/countdown-timer.vue
> +      if (this.seconds === 0) {
Maybe not momentjs

2021-02-05 18:02 UTC, Bedpaw commented on src/dictionary/language/pl.js
> +  }
done

2021-02-05 18:04 UTC, Bedpaw commented on src/components/molecules/countdown-timer.vue
> +import { getZeroPad } from 'utils/date';
It is adding zero "padding" to time format, it's popular name for this. idk if we should change it

2021-02-05 18:18 UTC, Bedpaw commented on src/components/molecules/countdown-timer.vue
> +  <div :style= "[minutes === 0 ? {color: 'red'} : {color: 'black'}]">
done

2021-02-08 16:48 UTC, dbetka commented on src/components/molecules/countdown-timer.vue
> +import { getZeroPad } from 'utils/date';
OK, approve

2021-02-08 16:49 UTC, dbetka commented on src/components/molecules/countdown-timer.vue
> +      if (this.seconds === 0) {
Create issue "Change moment.js to a different library" and close conversation

2021-02-08 19:41 UTC, Bedpaw commented on src/components/molecules/countdown-timer.vue
> +      if (this.seconds === 0) {
done

2021-02-08 19:43 UTC, merged