Issue/275/create view for adding new points
dbetka/harcmap pull request #305
Opened 2021-02-26 20:55 UTC by Bedpaw

#close #275
Help wanted:
Displaying messages and erros in add-new-point form
Force visual map update after point added

2021-03-01 18:38 UTC, dbetka commented
> Force visual map update after point added

Use that
```
  store.dispatch('event/download')
    .then(() => {
      if (uCheck.isObject(map.realMap)) {
        map.points.create({
          list: store.getters['event/getPointsVisibleOnMap'],
        });
      }
    })
    .catch(() => undefined);
```

2021-03-01 18:43 UTC, dbetka commented
> Displaying messages and erros in add-new-point form

Use `rules` param for date field.
Use `a-assist f-error` class for own error element.

2021-03-05 18:43 UTC, dbetka requested changes

2021-03-05 18:43 UTC, dbetka commented on src/components/molecules/map-pointer.vue
> +  name: 'm-map-pointer',
It should be `m-pointer-map` because this is pointer for map (in type of map)

2021-03-05 18:43 UTC, dbetka commented on src/components/organisms/map.vue
> +  <div style="height: 100%; position: relative">
Here should be `class` instead of `style`

2021-03-05 18:43 UTC, dbetka commented on src/components/organisms/map.vue
> +      const cookieDate = {
Should be `cookieData`

2021-03-05 18:43 UTC, dbetka commented on src/components/organisms/map.vue
> +    beforeDestroy () {
It's not standard method. It should be in main components object - it runs before component will be destroy

2021-03-05 18:43 UTC, dbetka commented on src/components/pages/admin/add-new-point.vue
> +        style="top:160px"
Here should be class - not style

2021-03-05 18:43 UTC, dbetka commented on src/components/pages/admin/add-new-point.vue
> +        style="position: relative; top:70px"
Here should be class - not style

2021-03-05 18:43 UTC, dbetka commented on src/components/pages/admin/add-new-point.vue
> +      style="top:-70px"
Here should be class - not style

2021-03-05 18:43 UTC, dbetka commented on src/components/pages/admin/set-new-point-position.vue
> +    <o-admin-set-new-point-position></o-admin-set-new-point-position>
`<o-admin-set-new-point-position/>`

2021-03-05 18:43 UTC, dbetka commented on src/dictionary/language/pl.js
> +    pointCategoryLevel: 'pozion',
`poziom`

2021-03-05 18:43 UTC, dbetka commented on src/map/index.js
> +export function updateMapFeatures () {
It should be in `export const map` object

2021-03-05 18:43 UTC, dbetka commented on src/map/index.js
> +export function updateMapFeatures () {
And should return promise. Example
```
export function updateMapFeatures () {
  const promise = store.dispatch('event/download')
  promise
    .then(() => {
      if (uCheck.isObject(map.realMap)) {
        map.points.create({
          list: store.getters['event/getPointsVisibleOnMap'],
        });
      }
    });

  return promise
}
```
because you use it later like promise function
```
// src/store/event.js:178
api.addPoint({ point, eventId })
  .then(() => updateMapFeatures())
```

2021-03-05 18:43 UTC, dbetka commented on src/utils/auto-update.js
> +      intervalID = setInterval(updateMapFeatures, intervalTime);
If `updateMapFeatures` will return promise remember to handle it here

2021-03-05 18:43 UTC, dbetka commented on src/utils/auto-update.js
> +    updateMapFeatures();
If `updateMapFeatures` will return promise remember to handle it here

2021-03-05 18:43 UTC, dbetka commented on src/utils/macros/random.js
> +function generateRandomString (length) {
`random.js` shouldn't be in `src/utils/macros/`. Better is `src/utils/`

2021-03-06 21:50 UTC, Bedpaw commented on src/utils/macros/random.js
> +function generateRandomString (length) {
done

2021-03-06 21:51 UTC, Bedpaw commented on src/dictionary/language/pl.js
> +    pointCategoryLevel: 'pozion',
done

2021-03-06 21:52 UTC, Bedpaw commented on src/components/pages/admin/add-new-point.vue
> +        style="top:160px"
Changed, fixed submit button and dont need tricks anymore

2021-03-06 21:52 UTC, Bedpaw commented on src/components/pages/admin/add-new-point.vue
> +        style="position: relative; top:70px"
Changed, fixed submit button and dont need tricks anymore

2021-03-06 22:01 UTC, Bedpaw commented on src/components/organisms/map.vue
> +  <div style="height: 100%; position: relative">
done

2021-03-06 22:11 UTC, Bedpaw commented on src/components/molecules/map-pointer.vue
> +  name: 'm-map-pointer',
done

2021-03-07 10:29 UTC, Bedpaw commented on src/map/index.js
> +export function updateMapFeatures () {
done

2021-03-07 10:29 UTC, Bedpaw commented on src/utils/auto-update.js
> +      intervalID = setInterval(updateMapFeatures, intervalTime);
done

2021-03-07 10:29 UTC, Bedpaw commented on src/utils/auto-update.js
> +    updateMapFeatures();
done

2021-03-10 08:28 UTC, dbetka requested changes

2021-03-10 08:28 UTC, dbetka commented on src/components/molecules/map-pointer.vue
> +  <div style="position:relative; z-index: 6">
change `style` to `class`

2021-03-10 08:28 UTC, dbetka commented on src/components/organisms/map.vue
> +  <div style="height: 100%; position: relative">
change `style` to `class`

2021-03-10 08:28 UTC, dbetka commented on src/components/pages/admin/add-new-point.vue
> +      />
Change message to snackbar for @dbetka

2021-03-10 08:28 UTC, dbetka commented on src/map/index.js
> +  }) {
Correct code style for @dbetka

2021-03-10 08:28 UTC, dbetka commented on src/utils/auto-update.js
> +      .catch(() => undefined);
catch errors in correct way for @dbetka

2021-03-10 08:28 UTC, dbetka commented on src/utils/macros.js
> +  pointDurationTime: 1, // 1000 * 60 * 60 temporary in hours
@Bedpaw what is that and why comment is not consistent to value

2021-03-10 08:28 UTC, dbetka commented on src/components/organisms/admin/set-point-position.vue
> +<style>
Unnecessary style @Bedpaw

2021-03-10 08:47 UTC, dbetka commented on src/utils/auto-update.js
> +      .catch(() => undefined);
done

2021-03-10 21:57 UTC, dbetka approved these changes

2021-03-10 21:57 UTC, merged