#304 Add /user/all endpoint. Turn off permission logs
dbetka/harcmap pull request #306
Opened 2021-03-01 18:52 UTC by HenoJurek

- Add /user/all endpoint that return list of authorized admin events users.
- Update swagger docu.
- Turn off permission logs.

2021-03-02 09:08 UTC, dbetka requested changes
To change

2021-03-02 09:08 UTC, dbetka commented on controllers/user/all.js
> +        res.send(filteredUsersList);
Front-end always gets response with `error` field.
I think response should be like below:
```
{
  users: [...],
  error: null
}
```

2021-03-02 09:16 UTC, dbetka commented
I've added front-end side functionality (API)

2021-03-02 17:13 UTC, dbetka requested changes

2021-03-02 17:13 UTC, dbetka commented on controllers/user/all.js
> +        }));
I also need an accountType

2021-03-04 12:02 UTC, HenoJurek commented on controllers/user/all.js
> +        res.send(filteredUsersList);
fixed

2021-03-04 12:02 UTC, HenoJurek commented on controllers/user/all.js
> +        }));
added

2021-03-04 12:18 UTC, merged