Fix bug collect point with is collected by another user
dbetka/harcmap pull request #333
Opened 2021-03-08 22:22 UTC by HenoJurek

- Fix collecting point with is collected by another user
- Add swagger info to README.md

2021-03-08 22:23 UTC, HenoJurek commented
@dbetka frontend need catch new error code - 1025 (POINT_ALREADY_COLLECTED). Now it show wrong info

2021-03-08 22:25 UTC, dbetka requested changes

2021-03-08 22:25 UTC, dbetka commented on lib/validateCodes.js
> +  POINT_ALREADY_COLLECTED: 1025,
@dbetka Handle this error on front-end side

2021-03-09 13:54 UTC, dbetka commented on lib/validateCodes.js
> +  POINT_ALREADY_COLLECTED: 1025,
done

2021-03-09 13:55 UTC, merged