System information endpoint
dbetka/harcmap pull request #445
Opened 2021-04-12 17:10 UTC by HenoJurek

2021-04-26 18:13 UTC, dbetka approved these changes

2021-04-26 18:33 UTC, dbetka requested changes

2021-04-26 18:33 UTC, dbetka commented on controllers/information.js
> +      appVersion: pjson.version,
Powinno być zwrócone pole `error: null` oraz `warn: null`

2021-04-27 21:41 UTC, HenoJurek commented on controllers/information.js
> +      appVersion: pjson.version,
fixed

2021-04-28 16:49 UTC, dbetka approved these changes

2021-04-28 17:51 UTC, merged