#458 Create geolocation api interface
dbetka/harcmap pull request #464
Opened 2021-06-21 18:57 UTC by Bedpaw

Close #458

2021-07-18 16:46 UTC, dbetka requested changes
Answer and fix @Bedpaw

2021-07-18 16:46 UTC, dbetka commented on src/utils/geolocation.js
> +      .catch(false);
Why `isEnabled` method return promise?
And why I get current position on `then` for code like below:
```
geolocationApi().isEnabled().then(value => console.log(value)) 
// console output: GeolocationPosition {coords: GeolocationCoordinates, timestamp: 1626626143515}
```

2021-07-18 16:46 UTC, dbetka commented on src/utils/geolocation.js
> +export const geolocationApi = () => {
`geolocationApi` function has appearance and few features typical for `class`. I need explanation why it's not write in class - we can talk about it.

2021-07-18 16:46 UTC, dbetka commented on src/utils/geolocation.js
> +  timeout: 0xFFFFFFFF,
Why timeout is equal `0xFFFFFFFF`?
What unit is using for `maximumAge`?

2021-07-22 18:25 UTC, Bedpaw commented
I will move this code to wdk repo and fix this issues there -> then I will close this pr

2021-08-18 16:51 UTC, closed without merging