Issue/508/rename window api and fix api imports
dbetka/harcmap pull request #510
Opened 2021-10-02 12:41 UTC by Bedpaw

2021-10-02 12:53 UTC, Bedpaw commented
- Add initDevTools function, where all dev mode changes are initilized.
- Add required api imports in some files

2021-10-03 08:23 UTC, dbetka requested changes
Idea with devTools is great! Good job!

2021-10-03 08:23 UTC, dbetka commented on src/components/organisms/map.vue
> +import { api } from '../../api';
Webpack has define alias for api. You can use it like below:
```
import { api } from 'api';
```

2021-10-03 08:23 UTC, dbetka commented on src/config/dev-tools.js
> +import { autoLogin } from '../utils/dev-mode/auto-login';
same like above:
```
import { autoLogin } from 'utils/dev-mode/auto-login';
```

2021-10-03 08:23 UTC, dbetka commented on src/config/index.js
> +  if (PRODUCTION === false) {
I have some doubts about putting it into config dir. Have you any rule what decide what should be in config path and what not?

2021-10-03 20:15 UTC, Bedpaw commented on src/config/index.js
> +  if (PRODUCTION === false) {
It is in building phase. Imo in config we should keep configurations and initialization of external resources and our buisnes logic config. In future we can split in further, but now i dont see better place. If you have any idea, please share it here.

2021-10-03 22:10 UTC, dbetka commented on src/config/index.js
> +  if (PRODUCTION === false) {
> It is in building phase. Imo in config we should keep configurations and initialization of external resources and our buisnes logic config. In future we can split in further, but now i dont see better place. If you have any idea, please share it here.

I thing it's ok for now

2021-10-03 22:11 UTC, dbetka commented
@Bedpaw Remember about README update. 🙂

2021-10-04 18:30 UTC, merged