#511 Add recomended solution for hiding navigation duplicated errors
dbetka/harcmap pull request #512
Opened 2021-10-02 12:51 UTC by Bedpaw

2021-10-03 08:25 UTC, dbetka commented
@Bedpaw rename branch from `isssue/511/hide-navigation-duplicated-error` to `issue/511/hide-navigation-duplicated-error`. Mistake is in `isssue`.

2021-10-03 08:35 UTC, dbetka requested changes
I have doubt... What if router push method make error different than duplicate one?

2021-10-03 19:53 UTC, Bedpaw commented
I found in docs that it can be even more specific just like you wanted :smile: 

> Added Router.NavigationFailureType.duplicated as second param

2021-10-04 17:22 UTC, dbetka approved these changes

2021-10-04 18:29 UTC, merged