Issue/535/create team page
dbetka/harcmap pull request #539
Opened 2021-11-14 16:30 UTC by CleverDarkSolutions

2021-11-16 17:58 UTC, Bedpaw commented on client/src/components/molecules/table-row/team-row.vue
> +    <div>{{this.$props.nickname}}</div>
this.$props.nickname === this.nickname

2021-11-16 18:00 UTC, Bedpaw commented on client/src/components/molecules/table-row/team-row.vue
> +  <div class="m-grid f-category-sum f-mb-1">
f-category-sum -> this class shouldn't be used as not category sum
Even if you want use the same styles you should create class for team-row to avoid coupling

2021-11-16 18:02 UTC, Bedpaw commented on client/src/dictionary/language/pl.js
> +      mainHeaderPartTwo: ' punktów',
I would suggest to not use space in translation

2021-11-16 18:10 UTC, Bedpaw commented on client/src/components/pages/team-view.vue
> +    members: [
```js
{
  "teamName": "string",
  "collectedPoints": [
    "string"
  ],
  "teamMembers": [
    {
      "email": "user@example.com",
      "userId": "string",
      "role": "string"
    }
  ]
}
```
1. Use proper names
2. You will not have isLeader field, you have to filter this list by role
3. As we disscuss at meeting, add icons based at role for each row

2021-11-16 18:11 UTC, Bedpaw commented on client/src/config/routes-config.ts
> +    icon: ICONS.settings,
Try to find some better icon

2021-11-16 18:22 UTC, Bedpaw commented on client/src/components/molecules/table-row/team-row.vue
> +    <div>{{this.$props.nickname}}</div>
also in templates this.nickname === nickname

2021-11-18 18:25 UTC, Bedpaw commented on client/src/components/pages/team-view.vue
> +        <m-row-team-row :user="user"
Strange enter

2021-11-18 18:32 UTC, Bedpaw commented
360px grid looks bad, it has to be fixed

2021-11-18 18:33 UTC, Bedpaw commented on client/src/components/pages/team-view.vue
> +    collectedPoints: '4200',
use sumOfCollectedPoints from user store. You wont get precise number from backend

2021-11-18 21:35 UTC, dbetka requested changes

2021-11-18 21:35 UTC, dbetka commented on client/src/components/pages/team-view.vue
> +      >
First attr should be in next line if there is many attrs. Example below:
```
<div 
  class="m-grid f-team-view"
  v-for="user in teamMembersOrdered"
  :key="user.userId"
>
```

2021-11-25 16:07 UTC, Bedpaw approved these changes

2021-11-26 15:24 UTC, dbetka requested changes

2021-11-26 15:44 UTC, dbetka commented on client/src/components/molecules/table-row/team-row.vue
> +    <div>{{user.email}}</div>
It will be fix in other issue #552

2021-11-26 15:45 UTC, dbetka approved these changes

2021-11-26 15:45 UTC, merged