Issue/536/advance game config
dbetka/harcmap pull request #543
Opened 2021-11-18 18:09 UTC by Bedpaw

closes #536

2021-11-18 21:31 UTC, dbetka requested changes
View looks good

2021-11-18 21:31 UTC, dbetka commented on client/src/components/organisms/admin/game-advanced-rules.vue
> +    >
Should be like that (indents):
```vue
<component  
  v-for="rule of advancedGameRules" :key="rule.ruleId"
  :is="inputTypeComponent(rule.ruleType)"
  v-model="rule.ruleValue"
  :disabled="blockForm"
  :assist="gameRulesUtils.getDescription(rule)"
  v-bind="inputProps(rule)"
  class="f-mb-2"
>
```

2021-11-18 21:31 UTC, dbetka commented on client/src/components/atoms/checkbox.vue
> +      ></a-icon>
Should be like below (tag close):
```vue
<a-icon
  :name="iconName"
  :type="ICONS_TYPES.outlined"
  :class="{'f-text-primary': hasFocus}"
/>
```

2021-11-18 21:31 UTC, dbetka commented on client/src/components/atoms/checkbox.vue
> +        <slot></slot>
```vue
<slot/>
```

2021-11-18 21:31 UTC, dbetka commented on client/src/config/event-config.ts
> +    }, {
```
}, {
```
to
```
}, 
{
```

2021-11-18 21:31 UTC, dbetka commented on client/src/utils/game-rules.ts
> +const getKeyFromOptions = (rule: GameRule) => getOptionsEnumAsArray(rule)[rule.ruleValue];
It should be without workaround like above. `ts-ignore` and `eslint-disable-next-line` is not safe solution.

2021-11-18 21:31 UTC, dbetka commented on client/src/dictionary/language/pl.js
> +      GeolocationAvailability: 'NOT IMPLEMENTED',
Translate `NOT IMPLEMENTED`

2021-11-18 21:31 UTC, dbetka commented on client/src/config/event-config.ts
> +    }, {
Or put it in one line:
```
mapRefreshTimeOptions: [
  { label: '1 min', value: secondsInMinute },
  { label: '5 min', value: 5 * secondsInMinute },
  ...
]
```

2021-11-22 16:52 UTC, Bedpaw commented on client/src/components/atoms/checkbox.vue
> +      ></a-icon>
done

2021-11-22 16:53 UTC, Bedpaw commented on client/src/config/event-config.ts
> +    }, {
...or use [].map, done :smile:

2021-11-22 16:53 UTC, Bedpaw commented on client/src/dictionary/language/pl.js
> +      GeolocationAvailability: 'NOT IMPLEMENTED',
Removed, we don't need this feature yet

2021-11-22 16:54 UTC, Bedpaw commented on client/src/utils/game-rules.ts
> +const getKeyFromOptions = (rule: GameRule) => getOptionsEnumAsArray(rule)[rule.ruleValue];
done

2021-11-22 18:18 UTC, dbetka requested changes

2021-11-22 18:18 UTC, dbetka commented on client/src/components/atoms/checkbox.vue
> -    />
Checkbox and text change color to green on focus. It look's strange.
![Screenshot from 2021-11-22 19-04-02](https://user-images.githubusercontent.com/6503362/142912715-bfc726cc-2120-4714-a95d-2902eeba0b37.png)
![Screenshot from 2021-11-22 19-03-56](https://user-images.githubusercontent.com/6503362/142912719-7ade24f4-0fe7-40c6-ba2a-f4d64f581a5c.png)

Maybe change opacity on 0.76 - like buttons

2021-11-22 18:18 UTC, dbetka commented on client/src/components/organisms/admin/game-advanced-rules.vue
> +      v-for="rule of advancedGameRules" :key="rule.ruleId"
Move `:key="rule.ruleId"` to next line

2021-11-22 18:18 UTC, dbetka commented on client/src/components/organisms/admin/game-advanced-rules.vue
> +      {{gameRulesUtils.getName(rule)}}
Add spaces before and after code in `{{ <code> }}`

2021-11-22 18:18 UTC, dbetka commented on client/src/router/utils.ts
Sometimes you're using semicolon and sometimes not. It should be standardized.

2021-11-24 07:48 UTC, Bedpaw commented on client/src/components/atoms/checkbox.vue
> -    />
Moved to backlog

2021-11-25 09:04 UTC, dbetka approved these changes

2021-11-25 16:06 UTC, merged