Issue/594/geolocation distance detection
dbetka/harcmap pull request #595
Opened 2022-04-04 16:21 UTC by Bedpaw

Branch based on #592 check it together or one by one

[] Introduce idea of feature toggles
[] Handle eventSettings after backend changes
[] Add POC of distance counting behind feature toggles

To see changes you need to enter map or event form with ?GPS=true in query params

2022-04-04 18:00 UTC, dbetka requested changes

2022-04-04 18:00 UTC, dbetka commented on client/src/utils/dev-mode/feature-toggle.ts
> +  FEATURE_TOGGLE_NAVIGATION: () => !!urlUtils.getQueryParam('GPS'),
I thing `Boolean()` will be better then twice exclamation mark - easier to read

2022-04-04 18:14 UTC, Bedpaw commented on client/src/utils/dev-mode/feature-toggle.ts
> +  FEATURE_TOGGLE_NAVIGATION: () => !!urlUtils.getQueryParam('GPS'),
For me !! is easier. Airbnb, which we use suggest also that it is better solution.

const age = 0;

// bad
const hasAge = new Boolean(age);

// good
const hasAge = Boolean(age);

// best
const hasAge = !!age;

2022-04-04 18:17 UTC, Bedpaw commented on client/src/map/features/myPosition.ts
> +    const conditionCheck = () => element.style.border === 'none';
It is for easier testing other option. example change backgroud color not border.
+ This is just POC to see how it would work not final design. It is behind feature toggle. We can discuss it

2022-04-04 18:18 UTC, dbetka commented on client/src/map/features/myPosition.ts
> +      element.style.border = `4px solid ${color}`;
To discuss

2022-04-04 18:18 UTC, Bedpaw commented on client/src/map/features/myPosition.ts
> +function getDistanceBetweenTwoCoords (mk1: {latitude: number, longitude: number}, mk2: {latitude: number, longitude: number}) {
Yes, I took first method that I find for POC :smile:
I will add comment, but we can change it when we do final solution

2022-04-04 18:18 UTC, Bedpaw commented on client/src/map/config.ts
> +  myPosition: {
Will change

2022-04-04 18:20 UTC, dbetka commented on client/src/utils/dev-mode/feature-toggle.ts
> +  FEATURE_TOGGLE_NAVIGATION: () => !!urlUtils.getQueryParam('GPS'),
I don't like it because it's less visible and clear on first look. :P

2022-04-04 18:21 UTC, dbetka commented on client/src/map/features/myPosition.ts
> +    const conditionCheck = () => element.style.border === 'none';
To discuss

2022-04-06 11:25 UTC, dbetka approved these changes

2022-04-07 08:11 UTC, merged