Issue/583/create user data edition endpoint
dbetka/harcmap pull request #597
Opened 2022-04-09 12:55 UTC by fzemi

#583

2022-04-18 16:26 UTC, HenoJurek requested changes

2022-04-18 16:26 UTC, HenoJurek commented on server/endpoints/v1/user/methods/edit-user.js
> +  if (!noUserEvents && userEvents) {
This condition should be one. You can edit variable `noUserEvents` to something like this: `(allUserEvents.length === 1 && !allUserEvents[0].eventId) || !userEvents` and rename this to `isUserEventsExist`

2022-04-18 16:26 UTC, HenoJurek commented on server/endpoints/v1/user/methods/edit-user.js
> +    for (const event of userEvents) {
Async/await function in for-of loops can be very slow. Try to change this to `forEach` loop with `await Promise.all`

2022-04-18 16:26 UTC, HenoJurek commented on server/endpoints/v1/user/methods/edit-user.js
> +          details: 'user is not assigned to at least one of the given events',
In most situations, `details` field is not necessary. It's enough to add new code in errorCodes with clear name and write it instead `errorCodes.CANNOT_UPDATE_USEREVENTS_NICKNAME`

2022-04-18 16:26 UTC, HenoJurek commented on server/endpoints/v1/user/methods/edit-user.js
> +    for (const event of userEvents) {
This also should be changed to forEach and Promise.all combination

2022-04-18 16:26 UTC, HenoJurek commented on server/endpoints/v1/user/methods/edit-user.js
> +    password: passwordToChange ? getSHA(newPassword) : userPassword,
`getSHA(newPassword)` can be moved up to variable because you use it in more places

2022-04-18 16:26 UTC, HenoJurek commented on server/endpoints/v1/user/specs/user.swagger.yml
> +                  $ref: '#/components/props/newPassword'
`props/newPassword` can be changed to `props/password`

2022-04-18 16:26 UTC, HenoJurek commented on server/specs/swagger-components/properties.swagger.yml
> +    newPassword:
This is not necessary

2022-04-18 16:26 UTC, HenoJurek commented on server/endpoints/v1/user/specs/user.swagger.yml
> +        - User
This is new tag "User", so you have to add it in `swagger.config.js` bellow `Users` tag

2022-04-18 20:00 UTC, fzemi commented on server/endpoints/v1/user/specs/user.swagger.yml
> +        - User
Done

2022-04-18 20:01 UTC, fzemi commented on server/specs/swagger-components/properties.swagger.yml
> +    newPassword:
Done

2022-04-18 20:01 UTC, fzemi commented on server/endpoints/v1/user/specs/user.swagger.yml
> +                  $ref: '#/components/props/newPassword'
Done

2022-04-18 20:01 UTC, fzemi commented on server/endpoints/v1/user/methods/edit-user.js
> +    password: passwordToChange ? getSHA(newPassword) : userPassword,
Done

2022-04-18 20:01 UTC, fzemi commented on server/endpoints/v1/user/methods/edit-user.js
> +          details: 'user is not assigned to at least one of the given events',
Done

2022-04-18 20:01 UTC, fzemi commented on server/endpoints/v1/user/methods/edit-user.js
> +    for (const event of userEvents) {
Done

2022-04-18 20:01 UTC, fzemi commented on server/endpoints/v1/user/methods/edit-user.js
> +  if (!noUserEvents && userEvents) {
Done

2022-04-18 20:01 UTC, fzemi commented on server/endpoints/v1/user/methods/edit-user.js
> +        details: 'old and new passwords are equal',
Done

2022-04-18 20:01 UTC, fzemi commented on server/endpoints/v1/user/methods/edit-user.js
> +        details: 'passwords do not match',
Done

2022-05-03 23:12 UTC, HenoJurek requested changes

2022-05-03 23:12 UTC, HenoJurek commented on server/endpoints/v1/user/specs/user.spec.js
> +        // errorDetails: 'passwords do not match',
This comments can be removed. Also in 131 line

2022-05-04 08:33 UTC, fzemi commented on server/endpoints/v1/user/specs/user.spec.js
> +        // errorDetails: 'passwords do not match',
Done

2022-05-06 14:47 UTC, HenoJurek requested changes

2022-05-09 19:39 UTC, fzemi commented on server/endpoints/v1/user/methods/edit-user.js
> +  const newPasswordHash = newPassword ? getSHA(newPassword) : null;
Done

2022-05-09 19:39 UTC, fzemi commented on server/endpoints/v1/user/methods/edit-user.js
> +          if (allUserEvents[i].teamId == null) allUserEvents[i].teamId = 'tempId';
Done

2022-05-16 19:39 UTC, HenoJurek approved these changes

2022-05-16 19:40 UTC, merged