Issue/612/teams tracks on map for admin
dbetka/harcmap pull request #620
Opened 2022-04-30 08:56 UTC by Bedpaw

[] Fix teamColor issue and show field in join event
[] Admin can see all teams track reflected with color
[] User can see all points, his points has stroke color with teamColor
[] Changes in downloadEvent for admin to fetch teams data
close #612

2022-05-03 19:33 UTC, dbetka requested changes
@Bedpaw ideas/comments worth to note for the future:
1. Let admin see which team has which color.
2. Let team members and leader see what color they have.
3. Maybe it's worth to have info which team collected point in point popup above map (only for admin?)

Few little comments about current code and functionality is in review comments

2022-05-03 19:33 UTC, dbetka commented on client/src/components/pages/join-event.vue
> +    const shouldDisplayTeamDetails = computed(() => event?.value?.role === ACCOUNT_TYPES.teamLeader);
it's not necessary to use question mark after event - it's always defined - only value of event can by null.

2022-05-03 19:33 UTC, dbetka commented on client/src/store/team.ts
> +  teamColor: '#447744',
default team color is needed here? #447744

2022-05-04 20:33 UTC, Bedpaw commented on client/src/components/pages/join-event.vue
> +    const shouldDisplayTeamDetails = computed(() => event?.value?.role === ACCOUNT_TYPES.teamLeader);
done

2022-05-04 20:33 UTC, Bedpaw commented on client/src/store/team.ts
> +  teamColor: '#447744',
removed

2022-05-04 20:45 UTC, dbetka approved these changes
Remember to note these comments and ideas on confluence: https://github.com/dbetka/harcmap/pull/620#pullrequestreview-960905870

Approve

2022-05-04 21:15 UTC, merged