Issue/581/add icon and splash screen for android and i os app
dbetka/harcmap pull request #635
Opened 2022-05-17 22:21 UTC by dbetka

close #581

2022-05-20 09:18 UTC, CleverDarkSolutions requested changes

2022-05-20 09:18 UTC, CleverDarkSolutions commented on client/android/app/src/main/res/values/colors.xml
> +    <color name="colorAccent">#ffffff</color>
Accent is a weird name imo, we can debate on this

2022-05-20 19:01 UTC, dbetka commented on client/android/app/src/main/res/values/colors.xml
> +    <color name="colorAccent">#ffffff</color>
I'll fix it

2022-05-22 10:03 UTC, CleverDarkSolutions requested changes

2022-05-22 18:09 UTC, dbetka commented on client/src/components/organisms/loading.vue
> +            {{ 'Oczekiwanie na połączenie z serwerem' }}
Translations will be added

2022-05-22 21:56 UTC, dbetka commented on client/android/app/src/main/res/values/colors.xml
> +    <color name="colorAccent">#ffffff</color>
Done

2022-05-22 21:56 UTC, dbetka commented on client/android/app/src/main/res/values/colors.xml
> +    <color name="colorAccent">#ffffff</color>
Done

2022-05-22 21:57 UTC, dbetka commented on client/src/components/organisms/loading.vue
> +            {{ 'Oczekiwanie na połączenie z serwerem' }}
Done

2022-06-27 19:01 UTC, merged