Issue/486/gps show user position
dbetka/harcmap pull request #646
Opened 2022-06-24 21:54 UTC by Bedpaw

Draft version of handling geolication and showing user position on map

2022-07-25 19:50 UTC, dbetka requested changes

2022-07-25 19:50 UTC, dbetka commented on client/src/components/organisms/map-settings-toggler.vue
> +      :class="{'f-display-none': !open }"
Space

2022-07-25 19:50 UTC, dbetka commented on client/src/components/organisms/map-settings-toggler.vue
> +        :size="'32'"
Instead `:size="'32'"` use `size="32"`

2022-07-25 19:50 UTC, dbetka commented on client/src/components/organisms/map-settings-toggler.vue
> +      bannerTimer.style.top = isOpen ? '239px' : 0;
Find better solution

2022-07-25 19:50 UTC, dbetka commented on client/src/components/organisms/map-settings.vue
> +  <template v-if="false">
To remove before merge

2022-07-25 19:50 UTC, dbetka commented on client/src/components/organisms/map-settings.vue
> +  <template v-if="false">
To remove before merge

2022-07-25 19:50 UTC, dbetka commented on client/src/map/controls/geolocation-control.ts
> +    return map.realMap.getControls().getArray().find((instance: Control) => instance instanceof GeolocationControl).element;
Find better solution

2022-07-25 19:50 UTC, dbetka commented on client/src/map/index.js
> +  panTo ({ latitude, longitude, zoom = 16 }) {
Check if current zoom is higher then 16

2022-07-25 19:50 UTC, dbetka commented on client/src/style/auto-import/components/molecules/banner-timer.sass
> +  background: white
Use variables

2022-07-25 19:50 UTC, dbetka commented on client/src/style/auto-import/components/molecules/countdown-time/countdown-timer-warning.sass
> +  color: #3FB25D
Use variables

2022-07-25 19:50 UTC, dbetka commented on client/src/style/auto-import/components/organisms/map-settings-toggler.sass
> +.f-map-settings-toggle-container
Do it something with it
`.o-container.f-map-settings-toggler`
`.o-container-map-settings-toggle`

2022-07-25 19:50 UTC, dbetka commented on client/src/style/auto-import/components/organisms/map-settings-toggler.sass
> +.f-map-settings-toggle-button
`.m-button.f-map-settings-toggle`

2022-07-25 19:50 UTC, dbetka commented on client/src/style/auto-import/components/organisms/map-settings.sass
> +.f-map-settings
.o-map-settings

2022-07-25 19:50 UTC, dbetka commented on client/src/style/vendors.sass
> +    color: #171717
Use variables

2022-07-25 19:50 UTC, dbetka commented on client/src/style/vendors.sass
> +    border-bottom: 1px solid #E6E6E6!important
Use variables

2022-07-25 19:50 UTC, dbetka commented on client/src/style/vendors.sass
> +  background-color: white!important
Use variables

2022-07-25 19:50 UTC, dbetka commented on client/src/utils/geolocation/geolocation-grade.ts
> +  setTimeout(() => isInitialized = true, timeToInitialize);
`setTimeout(() => (isInitialized = true), timeToInitialize);`

2022-07-25 19:50 UTC, dbetka commented on client/src/utils/geolocation/geolocation.ts
> +  console.log(now);
remove

2022-07-25 19:50 UTC, dbetka commented on client/src/utils/geolocation/geolocation.ts
> +  }
if (trackSub) return;

2022-08-01 20:48 UTC, Bedpaw commented on client/src/components/organisms/map-settings.vue
> +  <template v-if="false">
done

2022-08-01 20:48 UTC, Bedpaw commented on client/src/components/organisms/map-settings.vue
> +  <template v-if="false">
done

2022-08-01 20:48 UTC, Bedpaw commented on client/src/map/controls/geolocation-control.ts
> +    return map.realMap.getControls().getArray().find((instance: Control) => instance instanceof GeolocationControl).element;
added TODO

2022-08-01 20:48 UTC, Bedpaw commented on client/src/map/index.js
> +  panTo ({ latitude, longitude, zoom = 16 }) {
Fixed stange change zoom

2022-08-01 20:48 UTC, Bedpaw commented on client/src/style/vendors.sass
> +    border-bottom: 1px solid #E6E6E6!important
$Marble: #e6e6e6

2022-08-01 20:48 UTC, Bedpaw commented on client/src/style/vendors.sass
> +    color: #171717
$Dark_Gray: #171717

2022-08-01 20:48 UTC, Bedpaw commented on client/src/style/auto-import/components/molecules/banner-timer.sass
> +  background: white
done

2022-08-01 20:48 UTC, Bedpaw commented on client/src/style/auto-import/components/molecules/countdown-time/countdown-timer-warning.sass
> +  color: #3FB25D
done

2022-08-01 20:48 UTC, Bedpaw commented on client/src/style/vendors.sass
> +  background-color: white!important
done

2022-08-01 20:48 UTC, Bedpaw commented on client/src/style/vendors.sass
> +    border-bottom: 1px solid #E6E6E6!important
done

2022-08-01 20:48 UTC, Bedpaw commented on client/src/style/vendors.sass
> +    color: #171717
done

2022-08-01 20:48 UTC, Bedpaw commented on client/src/style/auto-import/components/organisms/map-settings.sass
> +.f-map-settings
done

2022-08-01 20:48 UTC, Bedpaw commented on client/src/style/auto-import/components/organisms/map-settings-toggler.sass
> +.f-map-settings-toggle-container
Changed to o-map-settings-toggle

2022-08-01 20:48 UTC, Bedpaw commented on client/src/style/auto-import/components/organisms/map-settings-toggler.sass
> +.f-map-settings-toggle-button
changed to m-map-settings-toggle-button

2022-08-01 20:49 UTC, Bedpaw commented on client/src/components/organisms/map-settings-toggler.vue
> +      :class="{'f-display-none': !open }"
done

2022-08-06 15:28 UTC, dbetka approved these changes

2022-08-06 15:31 UTC, merged