Issue/659/point destription and success message
dbetka/harcmap pull request #662
Opened 2022-07-25 18:46 UTC by fzemi

2022-07-25 19:56 UTC, dbetka requested changes
To fix

2022-07-25 19:56 UTC, dbetka commented on server/bin/mongodb/default-dump/points.dump.js
> +  pointSuccessMessage: 'Lorem ipsum dolor sit amet',
Null for timeout points

2022-07-25 19:57 UTC, dbetka commented on server/bin/mongodb/default-dump/points.dump.js
> +  pointSuccessMessage: 'Lorem ipsum dolor sit amet',
@fzemi

2022-08-01 20:16 UTC, fzemi commented on server/bin/mongodb/default-dump/points.dump.js
> +  pointSuccessMessage: 'Lorem ipsum dolor sit amet',
Done

2022-08-05 14:29 UTC, HenoJurek approved these changes
Looks good to me

2022-08-05 14:35 UTC, HenoJurek requested changes
Ops, i forgot about swagger docu. Please add documentation

2022-08-06 17:11 UTC, HenoJurek approved these changes

2022-08-06 17:20 UTC, dbetka approved these changes

2022-08-07 11:07 UTC, merged