Issue/653/admin user management
dbetka/harcmap pull request #690
Opened 2022-11-26 11:42 UTC by fzemi

Closes HAR-17

2022-12-19 20:55 UTC, HenoJurek requested changes

2022-12-19 20:55 UTC, HenoJurek commented on server/endpoints/v1/users/methods/update-user.js
> +  });
Do we have any validation for `userId`, does user with this id exist?

2022-12-19 20:55 UTC, HenoJurek commented on server/endpoints/v1/users/methods/update-user.js
> +    if (received.nickname) {
This can be write with destructuring(all variables from `received`)

2023-01-01 12:28 UTC, fzemi commented on server/endpoints/v1/users/methods/update-user.js
> +  });
Done

2023-01-01 12:28 UTC, fzemi commented on server/endpoints/v1/users/methods/update-user.js
> +    if (received.nickname) {
Done

2023-01-09 13:15 UTC, HenoJurek approved these changes

2023-01-09 21:00 UTC, merged