Issue/har 97/create event and point form
dbetka/harcmap pull request #718
Opened 2023-05-01 12:24 UTC by Bedpaw

2023-05-02 19:48 UTC, dbetka commented
Lack of visible validation below form fields.

<img width="330" alt="Screenshot 2023-05-02 at 21 02 34" src="https://user-images.githubusercontent.com/6503362/235761250-2698fd4b-62c7-44ab-aea2-d25fc43411d7.png">
<img width="324" alt="Screenshot 2023-05-02 at 21 03 10" src="https://user-images.githubusercontent.com/6503362/235761259-869da1a1-b061-4aa8-b2e4-26fc29c5d401.png">

2023-05-02 19:49 UTC, dbetka commented
After adding point form is not resetting its state.

<img width="325" alt="Screenshot 2023-05-02 at 21 48 15" src="https://user-images.githubusercontent.com/6503362/235770288-3470244e-0f50-4e43-ba7c-45805abdaf3c.png">

2023-05-02 19:51 UTC, dbetka commented
Allow select to take string or number via model value prop

<img width="620" alt="Screenshot 2023-05-02 at 21 01 01" src="https://user-images.githubusercontent.com/6503362/235770720-f355f720-478c-434a-9bfb-7150c1c94337.png">

2023-05-02 20:02 UTC, dbetka requested changes

2023-05-03 15:40 UTC, Bedpaw commented
> Allow select to take string or number via model value prop
> 
> <img alt="Screenshot 2023-05-02 at 21 01 01" width="620" src="https://user-images.githubusercontent.com/6503362/235770720-f355f720-478c-434a-9bfb-7150c1c94337.png">
Fixed

2023-05-03 15:51 UTC, Bedpaw commented
> Lack of visible validation below form fields (text and date fields and point position).
> 
> <img alt="Screenshot 2023-05-02 at 21 02 34" width="330" src="https://user-images.githubusercontent.com/6503362/235761250-2698fd4b-62c7-44ab-aea2-d25fc43411d7.png"><img alt="Screenshot 2023-05-02 at 21 03 10" width="324" src="https://user-images.githubusercontent.com/6503362/235761259-869da1a1-b061-4aa8-b2e4-26fc29c5d401.png">

Done for all expect event position, it require some discussion

2023-05-03 15:52 UTC, Bedpaw commented on client/src/features/map/map-position-picker.vue
done, but not sure if eslint applied as expected

2023-05-03 16:29 UTC, Bedpaw commented
> After adding point form is not resetting its state.
> 
> <img alt="Screenshot 2023-05-02 at 21 48 15" width="325" src="https://user-images.githubusercontent.com/6503362/235770288-3470244e-0f50-4e43-ba7c-45805abdaf3c.png">

Fixed

2023-05-03 18:10 UTC, dbetka approved these changes

2023-05-05 20:07 UTC, merged